name: delarosa
favicon: null
layout_spectrum: 0.37465
typography_spectrum: 0.7928178803995252
title: 'delarosa advertising & design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#6e6d6b'
    - '#facb03'
    - '#5f3400'
    - '#d8a025'
  brandStrength: 0.17902107443660498
  lightness: 0.38250660127960145
  saturation: 0.32743295514956117
  rhythmicContrast: 0.10887158173136413
purpose: []
